services:
  - type: web
    name: a3-fintech-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    plan: free
    branch: entrega
    envVars:
      - key: CORS_ORIGIN
        value: https://a3-fintech.vercel.app
      - key: NODE_VERSION
        value: "18"
