export const CITIES_MAPPING: Record<string, string> = {
  'sao paulo': 'São Paulo',
  'sp': 'São Paulo',
  'rio de janeiro': 'Rio de Janeiro',
  'rj': 'Rio de Janeiro',
  'belo horizonte': 'Belo Horizonte',
  'bh': 'Belo Horizonte',
  'brasília': 'Brasília',
  'df': 'Brasília',
  'curitiba': 'Curitiba',
  'pr': 'Curitiba',
  'salvador': 'Salvador',
  'ba': 'Salvador',
  'recife': 'Recife',
  'pe': 'Recife',
  'fortaleza': 'Fortaleza',
  'ce': 'Fortaleza',
  'manaus': 'Manaus',
  'am': 'Manaus',
  'porto alegre': 'Porto Alegre',
  'rs': 'Porto Alegre',
};

export const VALID_CATEGORIES = [
  'Eletrônicos',
  'Eletrodomésticos',
  'Serviços',
  'Vestuário',
  'Alimentos',
  'Outros',
];

export const MARKET_PRICES: Record<string, { min: number; max: number }> = {
  'Eletrônicos': { min: 50, max: 5000 },
  'Eletrodomésticos': { min: 100, max: 3000 },
  'Serviços': { min: 20, max: 1000 },
  'Vestuário': { min: 10, max: 500 },
  'Alimentos': { min: 5, max: 200 },
  'Outros': { min: 1, max: 10000 },
};

export const CATEGORY_KEYWORDS: Record<string, string[]> = {
  'Eletrônicos': [
    'notebook',
    'celular',
    'smartphone',
    'tablet',
    'tv',
    'câmera',
    'fone',
    'monitor',
    'computador',
    'console',
    'impressora',
    'iphone',
    'samsung',
    'lg',
  ],
  'Eletrodomésticos': [
    'geladeira',
    'fogão',
    'micro-ondas',
    'ar condicionado',
    'máquina lavar',
    'secadora',
    'forno',
    'liquidificador',
    'ventilador',
    'aquecedor',
    'brastemp',
    'electrolux',
  ],
  'Serviços': [
    'consultoria',
    'limpeza',
    'manutenção',
    'instalação',
    'reparo',
    'software',
    'hospedagem',
    'design',
    'serviço',
  ],
  'Vestuário': [
    'camiseta',
    'calça',
    'vestido',
    'bota',
    'sapato',
    'jaqueta',
    'bermuda',
    'blusa',
    'tênis',
    'meia',
    'roupa',
  ],
  'Alimentos': [
    'arroz',
    'feijão',
    'alimento',
    'comida',
    'bebida',
    'café',
    'açúcar',
    'sal',
    'azeite',
    'pão',
  ],
};
